# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'Flash Chat iOS18' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CLTypingLabel', '~> 0.4.0'

end
